<a href="https://colab.research.google.com/github/mdjespc/tutoring/blob/main/npmatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
from numpy import random as r

In [61]:
v = r.randint(0, 101, 10)
v

array([ 7, 53, 28, 66, 87, 78, 24, 16, 16, 39])

In [62]:
#                       GENERATOR
v_2 = np.fromiter((v[i] for i in range(1, len(v), 2)), dtype = int)
v_2

array([53, 66, 78, 16, 39])

In [63]:
v_3 = np.flip(v_2)
v_3

array([39, 16, 78, 66, 53])

In [64]:
dim = 5
m = np.linspace(6, 21, dim**2, dtype = float).reshape(dim, dim)
m = np.asmatrix(m)
m

matrix([[ 6.   ,  6.625,  7.25 ,  7.875,  8.5  ],
        [ 9.125,  9.75 , 10.375, 11.   , 11.625],
        [12.25 , 12.875, 13.5  , 14.125, 14.75 ],
        [15.375, 16.   , 16.625, 17.25 , 17.875],
        [18.5  , 19.125, 19.75 , 20.375, 21.   ]])

In [65]:
m_2 = np.flip(m, 1)
m_2

matrix([[ 8.5  ,  7.875,  7.25 ,  6.625,  6.   ],
        [11.625, 11.   , 10.375,  9.75 ,  9.125],
        [14.75 , 14.125, 13.5  , 12.875, 12.25 ],
        [17.875, 17.25 , 16.625, 16.   , 15.375],
        [21.   , 20.375, 19.75 , 19.125, 18.5  ]])

In [66]:
m_3 = np.flip(m, 0)
m_3

matrix([[18.5  , 19.125, 19.75 , 20.375, 21.   ],
        [15.375, 16.   , 16.625, 17.25 , 17.875],
        [12.25 , 12.875, 13.5  , 14.125, 14.75 ],
        [ 9.125,  9.75 , 10.375, 11.   , 11.625],
        [ 6.   ,  6.625,  7.25 ,  7.875,  8.5  ]])

In [67]:
m_4 = np.flip(m)
m_4

matrix([[21.   , 20.375, 19.75 , 19.125, 18.5  ],
        [17.875, 17.25 , 16.625, 16.   , 15.375],
        [14.75 , 14.125, 13.5  , 12.875, 12.25 ],
        [11.625, 11.   , 10.375,  9.75 ,  9.125],
        [ 8.5  ,  7.875,  7.25 ,  6.625,  6.   ]])

In [68]:
#The transpose of m is a matrix where the rows are turned into columns 
m_5 = m.T #ndarray.T ----> 'matrix' inherits 'ndarray'
m, m_5

(matrix([[ 6.   ,  6.625,  7.25 ,  7.875,  8.5  ],
         [ 9.125,  9.75 , 10.375, 11.   , 11.625],
         [12.25 , 12.875, 13.5  , 14.125, 14.75 ],
         [15.375, 16.   , 16.625, 17.25 , 17.875],
         [18.5  , 19.125, 19.75 , 20.375, 21.   ]]),
 matrix([[ 6.   ,  9.125, 12.25 , 15.375, 18.5  ],
         [ 6.625,  9.75 , 12.875, 16.   , 19.125],
         [ 7.25 , 10.375, 13.5  , 16.625, 19.75 ],
         [ 7.875, 11.   , 14.125, 17.25 , 20.375],
         [ 8.5  , 11.625, 14.75 , 17.875, 21.   ]]))

In [69]:
m_6 = m[1:-1,1:-1]
m_6

matrix([[ 9.75 , 10.375, 11.   ],
        [12.875, 13.5  , 14.125],
        [16.   , 16.625, 17.25 ]])

In [77]:
p = np.linspace(0, 252, 64, dtype = int).reshape(4, 4, 4)
p

array([[[  0,   4,   8,  12],
        [ 16,  20,  24,  28],
        [ 32,  36,  40,  44],
        [ 48,  52,  56,  60]],

       [[ 64,  68,  72,  76],
        [ 80,  84,  88,  92],
        [ 96, 100, 104, 108],
        [112, 116, 120, 124]],

       [[128, 132, 136, 140],
        [144, 148, 152, 156],
        [160, 164, 168, 172],
        [176, 180, 184, 188]],

       [[192, 196, 200, 204],
        [208, 212, 216, 220],
        [224, 228, 232, 236],
        [240, 244, 248, 252]]])

In [83]:
p_2 = p[1]
p_2

array([[ 64,  68,  72,  76],
       [ 80,  84,  88,  92],
       [ 96, 100, 104, 108],
       [112, 116, 120, 124]])