In [2]:
'''
    1-Create a one-dimensional array called v, with 10 integers. Each integer should be a random number between 1 and 100.
    2-Create a new array from v, which consists of the odd indices of previously created array v.
    3-Create another array from v, where the elements (columns) are in backwards ordering from v.
    4-Create a two-dimensional array called m with 25 evenly separated numbers from 6 to 21 inclusively in a 5 by 5 matrix.
    5-Create a new array from m, where the elements (columns) of each row are in reverse order.
    6-Create another array from m, where the rows are in reverse order.
    7-Create another array from m, where columns and rows are both in reverse order.
    8-Create another array from m, where the rows are made into columns (transform). Note difference from #7 above.
    9-Create another array from m, where the first and last row and the first and last column are cut off.
    10-Create a three-dimensional array called p, with 64 sequential numbers that are multiples of 4 in a three dimensional matrix.
    11-Create a new array from p, that includes only the second "layer" .
'''

import numpy as np

In [24]:
#Step 1
v = np.random.randint(0, 100, 10)
print(v)

[95 47 17 93 80  4 85 26 24 28]


In [25]:
#Step 2
o = np.array([x for x in v if x %2 != 0]) #o consists of all x values in v such that x is odd
print(o)

[95 47 17 93 85]


In [26]:
#Step 3
r = np.flip(v)
print(r)

[28 24 26 85  4 80 93 17 47 95]


In [38]:
#Step 4

min_val =  6
max_val = 21
dim = 5
#               min       max               step            extra method applied on what we just created
m = np.arange(min_val, max_val, (max_val-min_val)/(dim**2)).reshape(dim, dim)
print(m)

[[ 6.   6.6  7.2  7.8  8.4]
 [ 9.   9.6 10.2 10.8 11.4]
 [12.  12.6 13.2 13.8 14.4]
 [15.  15.6 16.2 16.8 17.4]
 [18.  18.6 19.2 19.8 20.4]]


In [42]:
#Step 5

rev_column_m = np.fliplr(m) #Flip left to right
print(rev_column_m)

[[ 8.4  7.8  7.2  6.6  6. ]
 [11.4 10.8 10.2  9.6  9. ]
 [14.4 13.8 13.2 12.6 12. ]
 [17.4 16.8 16.2 15.6 15. ]
 [20.4 19.8 19.2 18.6 18. ]]


In [43]:
#Step 6

rev_row_m = np.flipud(m) #Flip upside down
print(rev_row_m)

[[18.  18.6 19.2 19.8 20.4]
 [15.  15.6 16.2 16.8 17.4]
 [12.  12.6 13.2 13.8 14.4]
 [ 9.   9.6 10.2 10.8 11.4]
 [ 6.   6.6  7.2  7.8  8.4]]


In [47]:
#Step 7

rev_rc_m = np.flip(m) #Flip EVERYTHING :)
print(rev_rc_m)

[[20.4 19.8 19.2 18.6 18. ]
 [17.4 16.8 16.2 15.6 15. ]
 [14.4 13.8 13.2 12.6 12. ]
 [11.4 10.8 10.2  9.6  9. ]
 [ 8.4  7.8  7.2  6.6  6. ]]


In [52]:
#Step 8

#m_transpose = m.transpose()
m_transpose = np.array(m).T
print(m_transpose)

[[ 6.   9.  12.  15.  18. ]
 [ 6.6  9.6 12.6 15.6 18.6]
 [ 7.2 10.2 13.2 16.2 19.2]
 [ 7.8 10.8 13.8 16.8 19.8]
 [ 8.4 11.4 14.4 17.4 20.4]]


In [59]:
#Step 9

cut_m = (m[1:-1:, 1:-1:])
print(cut_m)

[[ 9.6 10.2 10.8]
 [12.6 13.2 13.8]
 [15.6 16.2 16.8]]


In [73]:
#Step 10

p = np.array([x for x in range(256) if x%4==0]).reshape(4, 4, 4) #Max range is 256
print(p)


[[[  0   4   8  12]
  [ 16  20  24  28]
  [ 32  36  40  44]
  [ 48  52  56  60]]

 [[ 64  68  72  76]
  [ 80  84  88  92]
  [ 96 100 104 108]
  [112 116 120 124]]

 [[128 132 136 140]
  [144 148 152 156]
  [160 164 168 172]
  [176 180 184 188]]

 [[192 196 200 204]
  [208 212 216 220]
  [224 228 232 236]
  [240 244 248 252]]]


In [74]:
#Step 11

p_layer2 = np.array(p[1])
print(p_layer2)

[[ 64  68  72  76]
 [ 80  84  88  92]
 [ 96 100 104 108]
 [112 116 120 124]]
